# Cloudflare Workers configuration
# Quick start: npx wrangler dev
# OR
# Install wrangler: npm install -g wrangler
# Deploy: wrangler deploy

name = "decide-pe-home"
main = "worker/worker.ts"
compatibility_date = "2025-10-30"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
preview_urls = false

# SPA configuration for serving React app
[assets]
# directory = "./dist"
# Not needed if using Vite plugin. See https://developers.cloudflare.com/workers/wrangler/configuration/#assets
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = [ "/" ]

[env.qa.assets]
binding = "ASSETS"
not_found_handling = "single-page-application"
# Comment out to test SEO worker in local mode
run_worker_first = ["/electometro/a"]

[route]
# Change pattern and zone_name randomly to preview locally (otherwise wrangler fails to load _headers)
pattern = "decide.pe"
zone_name = "decide.pe"
custom_domain = true

[env.qa.route]
pattern = "placeholder.com"
zone_name = "placeholder.com"
custom_domain = true

[vars]
ENVIRONMENT = "production"

[env.qa.vars]
# For local testing of SEO worker
ENVIRONMENT = "qa"

[[services]]
binding = "SEO_WORKER"
service = "decide-pe-seo-worker"

# YOU'LL NEED TO DEPLOY THE SEO-WORKER LOCALLY AND ADD env.qa.services IF YOU WANT TO TEST IT